version: "3"
services:
  cpp-kernelsoft-alpine:
    build:
      context: .
      dockerfile: Dockerfile
    image: cpp-kernelsoft-alpine
    container_name: cpp-kernelsoft-alpine
    volumes:
      - type: bind
        source: "./src"
        target: "/app"
    # command: bash -c "g++ -O2 -o main main.cpp && ./main"
    # stdin_open: true
    tty: true